### ISSUE TITLE
customerid column in credits table should be unique

### ISSUE THREAD

**Issue by kbaransk** [kbaransk/lemonpos#9]

**Comment by hiramvillarreal** [comment]
Hello buddy, thanks for your contributions, I am working doing a branch specially done for the raspberry Pi, using the GPIO to generate a pulse to open the cach drawer and a Mini thermal printer, 

https://www.youtube.com/watch?v=2-8U4ovjyZw

https://www.youtube.com/watch?v=FEUnnrYokXs

please contact me hiramvillarreal@hotmail.com
